ui_print "*********************************************************	"
ui_print "     ScreenCam Screen recorder systemizer					"
ui_print "     Developed by - Vijai chander							"
ui_print "     Source: https://gitlab.com/vijai/screenrecorder		"
ui_print "     ------------------Debug info--------------------		"
ui_print "     Android API    : $API								"
ui_print "     Magisk version : $MAGISK_VER							"
ui_print "     Arch           : $ARCH								"
ui_print "     Is magisk mode : $BOOTMODE							"
ui_print "     Module version : V4									"
ui_print "     ------------------------------------------------		"
ui_print "*********************************************************	"
